### ISSUE TITLE
选择菜单没有效果

### ISSUE THREAD

**Issue by fanjiehao886** [577528249/TTNews#7]
点击头部菜单没有反应。

**Comment by fanjiehao886** [comment]
I have already found the problem. Please add following codes!
`topContainerView.delegate = self;    //This is quite important !!!
    self.topContainerView = topContainerView;
    self.topContainerView.scrollView.delegate = self;`

**Comment by 577528249** [comment]
已经更新了，谢谢你发现并修复了这个bug，很惭愧自己没有太多时间去维护这个项目，如果你对这个项目有其他比较好的想法，你可以fork这个项目，新建一个分支，写好后pull requests到TTNews来，这样你就可以成为这个项目的contributor了，谢谢了！

**Comment by fanjiehao886** [comment]
ok,thanks!
